declare namespace NodeJS {
	import { TORUS_NETWORK_TYPE } from '@toruslabs/fetch-node-details'
	export interface ProcessEnv {
		GELATO_API_KEY: string
		NEXT_PUBLIC_ALCHEMY_POLYGON_RPC_URL: string
		NEXT_PUBLIC_APP_URL: string
		NEXT_PUBLIC_BASE_GEORLI_RPC_URL: string
		NEXT_PUBLIC_DATADOG_API_KEY: string
		NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: string
		NEXT_PUBLIC_JWT_SECRET: string
		NEXT_PUBLIC_MAGIC_API_KEY: string
		NEXT_PUBLIC_WEB3_AUTH_CLIENT_ID: string
		NEXT_PUBLIC_WEB3_AUTH_NETWORK: TORUS_NETWORK_TYPE
		MAGIC_API_SECRET: string
		PUBLIC_ADDRESS: string
		WEB3_AUTH_VERIFIER_ENCRYPTION_PASSPHRASE: string
		WEB3_AUTH_VERIFIER_KEY_ID: string
		NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: string
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string
		STRIPE_SECRET_KEY: string
		STRIPE_WEBHOOK_SECRET: string
	}
}
